# The Data
- You will be working with a heavily modified version of the Superheroes dataset from Kaggle.

**The dataset includes two csv's:**

superhero_info.csv:
Contains Name, Publisher, Demographic Info, and Body measurements.
superhero_powers.csv:
Contains Hero name and list of powers
The Task
Your task is two-fold:

**I. Clean the files and combine them into one final DataFrame.**

This dataframe should have the following columns:
- Hero (Just the name of the Hero)
- Publisher
- Gender
- Eye color
- Race
- Hair color
- Height (numeric)
- Skin color
- Alignment
- Weight (numeric)
Plus, one-hot-encoded columns for every power that appears in the dataset. E.g.:
- Agility
- Flight
- Superspeed
etc.
Hint: There is a space in "100 kg" or "52.5 cm"



**II. Use your combined DataFrame to answer the following questions.**

Compare the average weight of super powers who have Super Speed to those who do not.
What is the average height of heroes for each publisher?

# Import Libraries

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
## Importing the OS and JSON Modules
import os,json

# Read in the Data

In [5]:
df1 = pd.read_csv("Data\superhero_info - superhero_info.csv")
df2 = pd.read_csv("Data\superhero_powers - superhero_powers.csv")

In [6]:
df1.head()

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}"
2,Abin Sur|DC Comics,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}"
3,Abomination|Marvel Comics,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
4,Absorbing Man|Marvel Comics,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}"

In [7]:
df2.head()

    hero_names                                             Powers
0      3-D Man         Agility,Super Strength,Stamina,Super Speed
1       A-Bomb  Accelerated Healing,Durability,Longevity,Super...
2   Abe Sapien  Agility,Accelerated Healing,Cold Resistance,Du...
3     Abin Sur                                 Lantern Power Ring
4  Abomination  Accelerated Healing,Intelligence,Super Strengt...

In [8]:
df1.info() # This line of code gives an overlook of Data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 463 entries, 0 to 462
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Hero|Publisher  463 non-null    object
 1   Gender          463 non-null    object
 2   Race            463 non-null    object
 3   Alignment       463 non-null    object
 4   Hair color      463 non-null    object
 5   Eye color       463 non-null    object
 6   Skin color      463 non-null    object
 7   Measurements    463 non-null    object
dtypes: object(8)
memory usage: 29.1+ KB

In [9]:
df2.info() # This line of code gives an overlook of Data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 667 entries, 0 to 666
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   hero_names  667 non-null    object
 1   Powers      667 non-null    object
dtypes: object(2)
memory usage: 10.5+ KB

In [14]:
df1["Measurements"].value_counts()

{'Height': '183.0 cm', 'Weight': '90.0 kg'}     6
{'Height': '183.0 cm', 'Weight': '86.0 kg'}     6
{'Height': '178.0 cm', 'Weight': '79.0 kg'}     6
{'Height': '188.0 cm', 'Weight': '95.0 kg'}     6
{'Height': '180.0 cm', 'Weight': '81.0 kg'}     6
                                               ..
{'Height': '701.0 cm', 'Weight': '4.0 kg'}      1
{'Height': '185.0 cm', 'Weight': '89.0 kg'}     1
{'Height': '259.0 cm', 'Weight': '158.0 kg'}    1
{'Height': '191.0 cm', 'Weight': '65.0 kg'}     1
{'Height': '66.0 cm', 'Weight': '17.0 kg'}      1
Name: Measurements, Length: 287, dtype: int64

In [16]:
df1[["Hero", "Publisher"]] = df1["Hero|Publisher"].str.split('|',expand=True)
df1.head()

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero,Publisher
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics
2,Abin Sur|DC Comics,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}",Abin Sur,DC Comics
3,Abomination|Marvel Comics,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",Abomination,Marvel Comics
4,Absorbing Man|Marvel Comics,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}",Absorbing Man,Marvel Comics

In [17]:
df1 = df1.drop(columns = ["Hero|Publisher"]) # Correct and split this column
df1.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero,Publisher
0,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics
1,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics
2,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}",Abin Sur,DC Comics
3,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",Abomination,Marvel Comics
4,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}",Absorbing Man,Marvel Comics

In [18]:
df1 = df1[["Publisher","Hero","Gender","Race","Alignment","Hair color","Eye color","Skin color", "Measurements"]]
df1.head() # create an order that makes more sense

,Publisher,Hero,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements
0,Marvel Comics,A-Bomb,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
1,Dark Horse Comics,Abe Sapien,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}"
2,DC Comics,Abin Sur,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}"
3,Marvel Comics,Abomination,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
4,Marvel Comics,Absorbing Man,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}"

In [ ]:
find